apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: heart-mlops-ingress
spec:
  rules:
    - host: heart.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: heart-mlops-svc
                port:
                  number: 8000
